FROM python:3.7.3-slim-stretch

WORKDIR /code

RUN apt-get update && apt-get install -y --no-install-recommends \
  gcc \
  git \
  libc-dev \
  pkg-config \
  libsecp256k1-dev \
  rabbitmq-server \
  vim-tiny \
  lsof \
  && rm -rf /var/lib/apt/lists/*


COPY tbears-entry.sh /usr/local/bin
COPY . .
RUN pip install -r slot-machine/requirements.txt

ENTRYPOINT ["tbears-entry.sh"]